import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {CARDS} from '../build/idiom/config.js';
import {newGame,serializeGame,purchaseTicket,upgradeTech,SAVE_KEY} from '../build/idiom/wallet.js';
import {awardMilestones} from '../build/idiom/growth.js';
import {offerDraft} from '../build/idiom/run-build.js';
import {chooseRunBoost,rebirthPreview} from '../build/idiom/rebirth.js';
import {buyMachine,enqueueMachine,startMachine,advanceMachine,pauseMachine} from '../build/idiom/machine.js';
const base=resolve('.'),evidence=resolve('qa-evidence');await mkdir(evidence,{recursive:true});
const server=createServer(async(req,res)=>{try{const p=resolve(base,'.'+new URL(req.url,'http://localhost').pathname),file=p===base?resolve(base,'index.html'):p;if(!p.startsWith(base+'/')&&p!==base)throw Error('path');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png'})[extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end();}});
await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const page=await context.newPage(),errors=[],checks=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
const timeout=setTimeout(()=>{console.error('Rebirth browser QA exceeded 8 minutes');void browser.close();server.closeAllConnections();server.close();},480000);
const ready=()=>page.waitForFunction(()=>!!document.querySelector('#game-root')?.dataset.screen);
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('idiom-run-v31-base')));
async function install(s){await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:SAVE_KEY,raw:serializeGame(s)});await page.reload();await ready();assert.equal(await page.locator('#load-error').isVisible(),false);}
async function tab(name){await page.getByRole('button',{name:'永久成长',exact:true}).click();await page.locator(`[data-growth-tab=${name}]`).click();}
async function shot(name){if(await page.locator('.idiom-catalog').count())await page.locator('.idiom-catalog').evaluate(e=>e.scrollTop=0);await page.screenshot({path:resolve(evidence,name+'.jpg'),type:'jpeg',quality:85});}
const cdp=await context.newCDPSession(page);
async function touch(type,x,y){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,radiusX:2,radiusY:2,force:1}]});}
async function scratch(index){const cv=page.locator(`canvas[data-index="${index}"]`),b=await cv.boundingBox();assert.ok(b);const design=await cv.evaluate(e=>parseFloat(e.style.width));await touch('touchStart',b.x+b.width*.5,b.y+b.height*.2);
 for(let row=0,y=b.y+b.height*.14;y<b.y+b.height*.9;y+=b.width*22/design,row++){await touch('touchMove',b.x+b.width*(row%2?.9:.1),y);await touch('touchMove',b.x+b.width*(row%2?.1:.9),y);}await touch('touchEnd',0,0);
 await page.waitForFunction(i=>JSON.parse(localStorage.getItem('idiom-run-v31-base')).active.revealed.includes(i),index);
}
async function manualT01(){await page.getByRole('button',{name:'成语卡册',exact:true}).click();await page.locator('.idiom-card[data-card-id=T01]').click();await page.getByRole('button',{name:'买 一五一十 · 2元',exact:true}).click();await scratch(0);if((await saved()).active.settled===false)await page.getByRole('button',{name:/^领取 /}).click();}
function stock(id,seed){for(let attempt=0;attempt<100;attempt++){let s={...newGame(seed+':'+attempt),cash:10000000000000n,peak:10000000000000n,unlockedCount:18,bought:3,stats:{T01:{played:3,won:0,best:0n}},runStats:{T01:{played:3,won:0,best:0n}}};s={...s,runBuild:offerDraft(s.runBuild,s.runSeed,s.peak,3)};let selected=false;while(s.runBuild.pending){const choice=!selected&&s.runBuild.pending.options.includes(id)?id:null;if(choice)selected=true;s=chooseRunBoost(s,choice);}if(selected)return s;}throw Error('stock fixture');}
try{
 await page.goto(url);await ready();await tab('rebirth');assert.equal(await page.locator('[data-rebirth-action=preview]').isDisabled(),true);assert.equal(await page.locator('.idiom-reset-table tbody tr').count(),4);checks.push('New run shows reset/preserve table and blocks premature rebirth');
 for(let i=0;i<3;i++)await manualT01();assert.equal(await page.locator('#game-root').getAttribute('data-screen'),'build');assert.equal(await page.locator('[data-run-boost]').count(),3);
 const offer=(await saved()).runBuild.pending;await shot('rebirth-three-choices');await page.reload();await ready();assert.deepEqual((await saved()).runBuild.pending,offer);checks.push('Three real touch-scratched tickets trigger stable three choices across reload');
 await page.locator('[data-run-boost=hands]').click();assert.equal((await saved()).runBuild.stocks[0].used,0);assert.equal(await page.locator('[data-run-boost]').count(),0);await page.reload();await ready();assert.equal((await saved()).runBuild.stocks[0].id,'hands');
 await manualT01();assert.equal((await saved()).runBuild.stocks[0].used,1);assert.equal((await saved()).runBuild.speedCredits,1);checks.push('Choosing hands consumes one compatible manual ticket and grants one machine credit');
 await page.getByRole('button',{name:'自动机器',exact:true}).click();await page.getByRole('button',{name:'购买初级机 · 20元',exact:true}).click();await page.getByRole('button',{name:'升级到中级机 · 30元',exact:true}).click();
 await page.locator('[name=autoBuy]').check();await page.locator('[name=autoClaim]').check();await page.locator('[name=budget]').fill('2');await page.locator('[name=limit]').fill('1');await page.locator('[name=reserve]').fill('0');await page.locator('[data-machine-action=settings]').click();await page.locator('[data-machine-action=start]').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('idiom-run-v31-base')).machine.job?.elapsedMs>=500);await page.locator('[data-machine-action=pause]').click();const accelerated=await saved();assert.equal(accelerated.runBuild.speedCredits,0);assert.equal(accelerated.runBuild.stocks[0].used,1);
 await page.reload();await ready();assert.equal((await saved()).machine.job.elapsedMs,accelerated.machine.job.elapsedMs);await page.locator('[data-machine-action=start]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('idiom-run-v31-base')).machine.processed===1);checks.push('Machine uses credit once, leaves manual charges intact and resumes without refunding credit');
 const stats=Object.fromEntries(CARDS.slice(0,4).map(c=>[c.id,{played:3,won:0,best:0n}]));let s={...newGame('ui-rebirth'),cash:2000n,peak:2000n,bought:12,unlockedCount:4,stats,runStats:structuredClone(stats),history:[{nonce:'historic:1',cardId:'T01',prize:0n,status:'lost'}]};
 s={...s,progression:awardMilestones(s.progression,4,s.peak,stats)};for(const tech of ['luck','bonus','scratch'])s=upgradeTech(s,tech);
 s={...s,runBuild:offerDraft(s.runBuild,s.runSeed,s.peak,12)};s=chooseRunBoost(s,'hands');while(s.runBuild.pending)s=chooseRunBoost(s,null);s=buyMachine(buyMachine(s));s=pauseMachine(advanceMachine(startMachine(enqueueMachine(s,'T01',3)),300));await install(s);
 await page.locator('[data-machine-action=start]').click();await tab('rebirth');await page.locator('[data-rebirth-action=preview]').click();assert.equal((await saved()).machine.running,false);assert.equal(await page.locator('.idiom-dialog').isVisible(),true);assert.match(await page.locator('.idiom-dialog').textContent(),/已付费未结算票将作废/);
 const reviewed=await saved();await shot('rebirth-confirm-dialog');await page.locator('[data-rebirth-action=cancel]').click();assert.deepEqual(await saved(),reviewed);checks.push('Rebirth preview pauses running machine; cancel preserves the paid ticket, queue and wallet');
 await page.locator('[data-rebirth-action=preview]').click();const gain=rebirthPreview({...s,machine:{...s.machine,running:false}}).gain;await page.locator('[data-rebirth-action=confirm]').click();const born=await saved();
 assert.equal(born.cash,'60');assert.equal(born.peak,'60');assert.equal(born.unlockedCount,1);assert.equal(born.bought,0);assert.equal(born.machine.level,0);assert.equal(born.machine.queue.length,0);assert.equal(born.active,null);assert.equal(born.runBuild.stocks.length,0);assert.deepEqual(born.runStats,{});
 assert.deepEqual(born.progression.levels,reviewed.progression.levels);assert.deepEqual(born.progression.claimed,reviewed.progression.claimed);assert.equal(born.progression.points,reviewed.progression.points+gain);assert.equal(born.rebirth.count,1);assert.equal(born.rebirth.records[0].discarded,reviewed.active.nonce);assert.deepEqual(born.stats,reviewed.stats);assert.deepEqual(born.history,reviewed.history);
 await page.reload();await ready();assert.equal((await saved()).progression.points,born.progression.points);assert.equal((await saved()).rebirth.count,1);await tab('rebirth');assert.equal(await page.locator('[data-rebirth-action=preview]').isDisabled(),true);await shot('rebirth-after-reset');checks.push('Confirmed rebirth resets only run assets, pays once and preserves permanent growth/history across reload');
 await page.getByRole('button',{name:'自动机器',exact:true}).click();await page.getByRole('button',{name:'购买初级机 · 20元',exact:true}).click();assert.equal(await page.locator('[name=autoBuy]').isDisabled(),false);await page.locator('[name=autoBuy]').check();await page.locator('[name=autoClaim]').check();await page.locator('[data-machine-action=settings]').click();await page.reload();await ready();await page.getByRole('button',{name:'自动机器',exact:true}).click();assert.equal((await saved()).machine.level,1);assert.equal((await saved()).machine.autoBuy,true);checks.push('Permanent automation permission works on the new level-one machine and survives restore');
 const hinted=purchaseTicket(stock('hint','ui-hint'),'T09');await install(hinted);assert.equal(await page.locator('canvas[data-public-safe=true]').count(),1);assert.equal(await page.locator('canvas[data-index]').count(),10);const safe=hinted.active.publicSafeIndex;await scratch(safe);assert.equal((await saved()).active.revealed.length,1);assert.equal((await saved()).active.settled,false);await page.reload();await ready();assert.equal((await saved()).active.publicSafeIndex,safe);await shot('rebirth-public-safe');checks.push('Public safe hint is visible, does not auto reveal all safe cells and remains fixed across reload');
 let guarded;for(let n=0;n<1000;n++){const t=purchaseTicket(stock('guard','ui-guard'+n),'T11');if(t.active.committedLayout[0].kind==='money'&&t.active.committedLayout[1].kind==='bomb'){guarded=t;break;}}
 await install(guarded);await scratch(0);await scratch(1);assert.equal(await page.locator('#game-root').getAttribute('data-status'),'won');const unpaid=await saved();await page.getByRole('button',{name:'领取 10万元',exact:true}).click();const paid=await saved();assert.equal(BigInt(paid.cash),BigInt(unpaid.cash)+100000n);await page.reload();await ready();assert.equal((await saved()).cash,paid.cash);await shot('rebirth-guard-result');checks.push('Real cashout bomb preserves only the visible subtotal and pays exactly once');
 await tab('rebirth');for(const view of [{width:360,height:640},{width:844,height:390},{width:1280,height:900}]){await page.setViewportSize(view);const b=await page.locator('#game-root').boundingBox();assert.ok(b.x>=-1&&b.y>=-1&&b.x+b.width<=view.width+1&&b.y+b.height<=view.height+1);assert.equal(await page.locator('.idiom-catalog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);await shot('rebirth-'+view.width+'x'+view.height);}checks.push('Rebirth table, tabs and controls fit three viewport sizes without horizontal overflow');
 const other=await context.newPage();await other.goto(url);await other.waitForFunction(()=>!!document.querySelector('#game-root')?.dataset.screen);assert.equal(await other.locator('#game-root').getAttribute('data-read-only'),'true');await other.getByRole('button',{name:'永久成长',exact:true}).click();await other.locator('[data-growth-tab=rebirth]').click();assert.equal(await other.locator('[data-rebirth-action=preview]').isDisabled(),true);await other.close();checks.push('Second page cannot initiate a rebirth without the writer lock');
 const original=await saved(),broken=structuredClone(original);broken.progression.earned++;const raw=JSON.stringify(broken);await page.evaluate(v=>localStorage.setItem('idiom-run-v31-base',v),raw);await page.reload();await page.waitForSelector('#load-error:not([hidden])');assert.equal(await page.evaluate(()=>localStorage.getItem('idiom-run-v31-base')),raw);await page.evaluate(v=>localStorage.setItem('idiom-run-v31-base',v),JSON.stringify(original));await page.reload();await ready();checks.push('Invalid fortune ledger displays an error and retains the original save text');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({rebirthChecks:checks.length,checks,pageErrors:errors},null,2));
}finally{clearTimeout(timeout);await browser.close();server.closeAllConnections();server.close();}
